### ISSUE TITLE
[DipEncoder] Init parameters not recognized

### ISSUE THREAD

**Issue by Han007** [collinleiber/ClustPy#95]
Hello, 

I am trying to use the DipEncoder class for a project. It's a very interesting model for the problem I am trying to solve as it allows for intrinsic optimization of the number of clusters. However, some of the initialization parameters appear to not exist. In particular, the ones commented it below: 

`dipencoder = DipEncoder(

    n_clusters= 10, # Can be None if a corresponding initial_clustering_class is given, e.g. DBSCAN
    batch_size = 256, # if None then set 3*n_clusters

    #pretrain_optimizer_params = {'lr': 1e-3}, # parameters of the optimizer for the pretraining of the neural network, includes the learning rate (default: {“lr”: 1e-3})
    #clustering_optimizer_params = {'lr': 1e-4}, # parameters of the optimizer for the actual clustering procedure, includes the learning rate (default: {“lr”: 1e-4})

    pretrain_epochs = 100, # number of epochs for the pretraining of the neural network (default: 100)
    clustering_epochs= 100, #  number of epochs for the actual clustering procedure (default: 100)

    optimizer_class = torch.optim.Adam, # the optimizer class (default: torch.optim.Adam)
    #ssl_loss_fn = torch.nn.MSELoss(), # reconstruction loss for autoencoders (default: torch.nn.MSELoss())

    #neural_network = None,
    #neural_network_weights = None,
    embedding_size = 10, # size of the embedding within the neural network (default: 10)

    max_cluster_size_diff_factor=3,
    #clustering_loss_weight= 1.0, #  weight of the clustering loss (default: 1.0)
    #ssl_loss_weight=None, #weight of the self-supervised learning (ssl) loss. If None, it will be equal to 1/(4L), where L is the reconstruction loss of the first batch of an untrained neural network (default: None)
    #custom_dataloaders = None,
    #augmentation_invariance = False,

    #initial_clustering_class = KMeans, #clustering class to obtain the initial cluster labels after the pretraining (default: KMeans)
    #initial_clustering_params = {},
    #device = 'cuda',
    random_state = 42

    )`

For the problem I am trying to solve, I would need to be able to set an initial_clustering_class with n_clusters = None. 

If I try to initialize the class with initial_clustering_class = KMeans and n_clusters = None, I get the following error: 
TypeError: DipEncoder.__init__() got an unexpected keyword argument 'initial_clustering_class'

Could you let me know if I'm implementing this the wrong way? 

Please let me know what additional information you may need.

Thank you very much!

**Comment by collinleiber** [comment]
Hi,

I assume that there is a problem with the ClustPy version. In the 0.0.1 release, the initial_clustering_class parameter did not yet exist and there seem to have been problems with the appropriate documentation.
However, we have published a new release today (version 0.0.2) which can be installed via pip. Here, everything should work properly.

Further, note that DipEncoder cannot by itself determine the number of clusters. The hyperparameter n_clusters can only be None if the algorithm referenced by initial_clustering_class is able to determine the number of clusters (e.g. DBSCAN, XMeans or GMeans). However, this is not the case with KMeans.
If a suitable algorithm is chosen, the number of clusters is estimated directly after the autoencoder is pretrained and then remains unchanged during the deep clustering training. Therefore, the DipDECK algorithm may be more suitable for your task.

**Comment by Han007** [comment]
Hi, 

Thank you for your answer! I followed your advice and am trying to implement DipDECK from ClustPy's latest version (0.0.2), initializing the number of clusters as None to obtain the optimal k. However, doing so I get the following error: 

File "/usr/local/lib/python3.10/dist-packages/clustpy/deep/dipdeck.py", line 707, in fit
    labels, n_clusters, centers, neural_network = _dip_deck(X, self.n_clusters_init, self.dip_merge_threshold,
  File "/usr/local/lib/python3.10/dist-packages/clustpy/deep/dipdeck.py", line 104, in _dip_deck
    if n_clusters_init < min_n_clusters and n_clusters_init is not None:
TypeError: '<' not supported between instances of 'NoneType' and 'int'

Would it be possible to check this or provide an example of the implementation with n_clusters_init = None?
Thanks again!

**Comment by collinleiber** [comment]
I think you actually spotted a bug there, which we will fix in a future release.
However, this shouldn't be a major issue. The idea of DipDECK is to set an upper bound for the number of clusters using n_clusters_init.
The algorithm will then optimize this value during the execution. For example, it could be that you set n_clusters_init=40 and the final n_clusters will be 10. 
```
dipdeck = DipDECK(n_clusters_init=40)
dipdeck.fit(data)
print(dipdeck.n_clusters_)
```
Here, dipdeck.n_clusters_ returns the final number of clusters.

Alternatively, you can do what you proposed in the first post and use some arbitrary deep clustering algorithm, e.g., DipEncoder, combined with a cluster initialization that can estimate the number of clusters. In this case, as already mentioned, the number of clusters will be chosen directly after pretraining the neural network but not during the optimization of the specific deep clustering loss.
```
from clustpy.partition import XMeans
import numpy as np
dipencoder = DipEncoder(n_clusters=None, batch_size=256, initial_clustering_class=XMeans)
dipencoder .fit(data)
print(np.unique(dipencoder.labels_).shape[0])
```

**Comment by Han007** [comment]
Great, thank you for the explanations. I will continue using DipDECK for now. Is it possible to obtain the"confidence score" with which a data point is assigned to a certain cluster? 
Thanks again!

**Comment by collinleiber** [comment]
Unfortunately, DipDECK does not provide a confidence score for the assignments

**Comment by max6457** [comment]
Hello, is the bug already fixed? When using DipEncoder with intiial_clustering_class and n_clusters=None, I still get the following error: 
{
	"name": "TypeError",
	"message": "unsupported operand type(s) for *: 'int' and 'NoneType'",
	"stack": "---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[45], line 1
----> 1 cls = DipEncoder(device='cuda', initial_clustering_class=XMeans, n_clusters=None) #DipNSub

File c:\\Users\\XXX\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\clustpy\\deep\\dipencoder.py:757, in DipEncoder.__init__(self, n_clusters, batch_size, pretrain_optimizer_params, clustering_optimizer_params, pretrain_epochs, clustering_epochs, optimizer_class, ssl_loss_fn, neural_network, neural_network_weights, embedding_size, max_cluster_size_diff_factor, clustering_loss_weight, ssl_loss_weight, custom_dataloaders, augmentation_invariance, initial_clustering_class, initial_clustering_params, device, random_state)
    747 def __init__(self, n_clusters: int, batch_size: int = None, pretrain_optimizer_params: dict = None,
    748              clustering_optimizer_params: dict = None, pretrain_epochs: int = 100,
    749              clustering_epochs: int = 100, optimizer_class: torch.optim.Optimizer = torch.optim.Adam,
   (...)
    755              initial_clustering_class: ClusterMixin = KMeans, initial_clustering_params: dict = None,
    756              device: torch.device = None, random_state: np.random.RandomState | int = None):
--> 757     super().__init__(25 * n_clusters if batch_size is None else batch_size, neural_network, neural_network_weights,
    758                      embedding_size, device, random_state)
    759     self.n_clusters = n_clusters
    760     self.pretrain_optimizer_params = {
    761         \"lr\": 1e-3} if pretrain_optimizer_params is None else pretrain_optimizer_params

TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'"
}
